### ISSUE TITLE
[PE-D][Tester C] Name in appointment does not update after editing original name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-3/tp#161]
![appointments_dont_update_after_edit.png](https://raw.githubusercontent.com/lilozz2/ped/main/files/7d7d7034-e663-4d42-ab05-54676ca4b671.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lilozz2/ped#1

**Comment by techjay-c** [comment]
This is a limitation of our Appointment feature. We will improve this feature flaw in v1.5
