### ISSUE TITLE
[PE-D][Tester C] list treatment message ends with a comma

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-3/tp#165]
![list_treatments_end_comma.png](https://raw.githubusercontent.com/lilozz2/ped/main/files/d7ecb9f8-a659-42c5-b1a4-9defcc1604f4.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: lilozz2/ped#3

**Comment by ruth-lim** [comment]
#169

**Comment by techjay-c** [comment]
This is classified as a cosmetic flaw and will be worked on in future implementations
