### ISSUE TITLE
[PE-D][Tester C] Quick Notes functionality undocumented & unable to save

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W10-3/tp#173]
![image.png](https://raw.githubusercontent.com/lilozz2/ped/main/files/255a9697-19a9-4338-974a-49996e27e617.png)

Steps to replicate:
After text has been entered in the box, and the save button is entered, nothing really happens so not sure if this is intended behaviour or not. Furthermore there is no mention of this in the UG or at least a quick glance and search through the table of context does not show how it should work

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lilozz2/ped#6

**Comment by ruth-lim** [comment]
Issue raised is intended behaviour.

## TODO:
Improve documentation on Quick Notes.

**Comment by ruth-lim** [comment]
#199
