### ISSUE TITLE
[PE-D][Tester A] Dentist with 0 YOE does not display properly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-3/tp#181]
![image.png](https://raw.githubusercontent.com/fuyiqiao/ped/main/files/5ec4ee85-5c11-4d58-acf7-e067917c5f19.png)

After the dentist with ID1 is edited to have YOE of 0, the experience section becomes empty.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: fuyiqiao/ped#5

**Comment by ruth-lim** [comment]
#162
