### ISSUE TITLE
[PE-D][Tester E] Cosmetic issue with right click menu in command result box

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-3/tp#184]
As described in title

![Screenshot 2023-11-03 at 5.01.10 PM.png](https://raw.githubusercontent.com/zhonghan721/ped/main/files/a8595fd7-1b8a-45f8-b39f-48d7f4eca59d.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: zhonghan721/ped#6

**Comment by qyaner** [comment]
Cosmetic issue so will be handled in future enhancements
