### ISSUE TITLE
[PE-D][Tester A] Email and Specialisation fields are hidden instead of wrapped around

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-3/tp#188]
![image.png](https://raw.githubusercontent.com/fuyiqiao/ped/main/files/1aac7374-ce71-4fa2-a813-a791b3421c61.png)

Email and Specialisation fields are hidden instead of wrapped around. User is unable to view important information like the dentist's specialization at a glance.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: fuyiqiao/ped#8

**Comment by ruth-lim** [comment]
Cosmetic issue. Can be worked around by resizing window.
Long email is an edge case.
